controllers:
    resource: ../../src/Controller/
    type: annotation


# admin:
#    resource: ../../src/Controller/Admin/
#    type: annotation
#    prefix: '/m/admin'


kernel:
    resource: ../../src/Kernel.php
    type: annotation
