<?php

namespace ContainerL26vbvb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IfaUx1PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IfaUx1P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IfaUx1P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contact' => ['privates', '.errored..service_locator.IfaUx1P.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.IfaUx1P": it references class "App\\Entity\\Contact" but no such service exists.'],
        ], [
            'contact' => 'App\\Entity\\Contact',
        ]);
    }
}
