<?php

namespace ContainerEnM7p8F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NfYd6vOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nfYd6vO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nfYd6vO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'combat' => ['privates', '.errored..service_locator.nfYd6vO.App\\Entity\\Combat', NULL, 'Cannot autowire service ".service_locator.nfYd6vO": it references class "App\\Entity\\Combat" but no such service exists.'],
        ], [
            'combat' => 'App\\Entity\\Combat',
        ]);
    }
}
