<?php

namespace ContainerEnM7p8F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PY5H1rJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PY5H1rJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PY5H1rJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'combat' => ['privates', '.errored..service_locator.PY5H1rJ.App\\Entity\\Combat', NULL, 'Cannot autowire service ".service_locator.PY5H1rJ": it references class "App\\Entity\\Combat" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'combat' => 'App\\Entity\\Combat',
            'entityManager' => '?',
        ]);
    }
}
