<?php

namespace ContainerEnM7p8F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCombatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PY5H1rJ.App\Entity\Combat' shared service.
     *
     * @return \App\Entity\Combat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PY5H1rJ": it references class "App\\Entity\\Combat" but no such service exists.');
    }
}
