<?php

namespace Container90bGhCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IBsT8cYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iBsT8cY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iBsT8cY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'combatRepository' => ['privates', 'App\\Repository\\CombatRepository', 'getCombatRepositoryService', true],
        ], [
            'combatRepository' => 'App\\Repository\\CombatRepository',
        ]);
    }
}
