<?php

namespace Container90bGhCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DtaNb9QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dtaNb9Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dtaNb9Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService', true],
            'persoRepository' => ['privates', 'App\\Repository\\PersoRepository', 'getPersoRepositoryService', true],
        ], [
            'newsRepository' => 'App\\Repository\\NewsRepository',
            'persoRepository' => 'App\\Repository\\PersoRepository',
        ]);
    }
}
