<?php

namespace Container90bGhCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DRlW2FjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dRlW2Fj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dRlW2Fj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\DashboardController::ContactGestiton' => ['privates', '.service_locator.BlcLmcA', 'get_ServiceLocator_BlcLmcAService', true],
            'App\\Controller\\Admin\\DashboardController::UserGestion' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\Admin\\DashboardController::delete' => ['privates', '.service_locator.iToh589', 'get_ServiceLocator_IToh589Service', true],
            'App\\Controller\\Admin\\DashboardController::view' => ['privates', '.service_locator.IfaUx1P', 'get_ServiceLocator_IfaUx1PService', true],
            'App\\Controller\\BaseController::home' => ['privates', '.service_locator.dtaNb9Q', 'get_ServiceLocator_DtaNb9QService', true],
            'App\\Controller\\CombatController::accept' => ['privates', '.service_locator.PY5H1rJ', 'get_ServiceLocator_PY5H1rJService', true],
            'App\\Controller\\CombatController::ajaxData' => ['privates', '.service_locator.iBsT8cY', 'get_ServiceLocator_IBsT8cYService', true],
            'App\\Controller\\CombatController::create' => ['privates', '.service_locator.FWqM42_', 'get_ServiceLocator_FWqM42Service', true],
            'App\\Controller\\CombatController::fight' => ['privates', '.service_locator.nfYd6vO', 'get_ServiceLocator_NfYd6vOService', true],
            'App\\Controller\\CombatController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\CombatController::wait' => ['privates', '.service_locator.nfYd6vO', 'get_ServiceLocator_NfYd6vOService', true],
            'App\\Controller\\CombatController::waitData' => ['privates', '.service_locator.nfYd6vO', 'get_ServiceLocator_NfYd6vOService', true],
            'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.60bJY.Q', 'get_ServiceLocator_60bJY_QService', true],
            'App\\Controller\\NewsController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PersoController::create' => ['privates', '.service_locator.4UFIY6Q', 'get_ServiceLocator_4UFIY6QService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator._60ahW5', 'get_ServiceLocator_60ahW5Service', true],
            'App\\Controller\\RegistrationController::registerVerificationEmail' => ['privates', '.service_locator.cItq8lq', 'get_ServiceLocator_CItq8lqService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Admin\\DashboardController:ContactGestiton' => ['privates', '.service_locator.BlcLmcA', 'get_ServiceLocator_BlcLmcAService', true],
            'App\\Controller\\Admin\\DashboardController:UserGestion' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\Admin\\DashboardController:delete' => ['privates', '.service_locator.iToh589', 'get_ServiceLocator_IToh589Service', true],
            'App\\Controller\\Admin\\DashboardController:view' => ['privates', '.service_locator.IfaUx1P', 'get_ServiceLocator_IfaUx1PService', true],
            'App\\Controller\\BaseController:home' => ['privates', '.service_locator.dtaNb9Q', 'get_ServiceLocator_DtaNb9QService', true],
            'App\\Controller\\CombatController:accept' => ['privates', '.service_locator.PY5H1rJ', 'get_ServiceLocator_PY5H1rJService', true],
            'App\\Controller\\CombatController:ajaxData' => ['privates', '.service_locator.iBsT8cY', 'get_ServiceLocator_IBsT8cYService', true],
            'App\\Controller\\CombatController:create' => ['privates', '.service_locator.FWqM42_', 'get_ServiceLocator_FWqM42Service', true],
            'App\\Controller\\CombatController:fight' => ['privates', '.service_locator.nfYd6vO', 'get_ServiceLocator_NfYd6vOService', true],
            'App\\Controller\\CombatController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\CombatController:wait' => ['privates', '.service_locator.nfYd6vO', 'get_ServiceLocator_NfYd6vOService', true],
            'App\\Controller\\CombatController:waitData' => ['privates', '.service_locator.nfYd6vO', 'get_ServiceLocator_NfYd6vOService', true],
            'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.60bJY.Q', 'get_ServiceLocator_60bJY_QService', true],
            'App\\Controller\\NewsController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PersoController:create' => ['privates', '.service_locator.4UFIY6Q', 'get_ServiceLocator_4UFIY6QService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator._60ahW5', 'get_ServiceLocator_60ahW5Service', true],
            'App\\Controller\\RegistrationController:registerVerificationEmail' => ['privates', '.service_locator.cItq8lq', 'get_ServiceLocator_CItq8lqService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Admin\\DashboardController::ContactGestiton' => '?',
            'App\\Controller\\Admin\\DashboardController::UserGestion' => '?',
            'App\\Controller\\Admin\\DashboardController::delete' => '?',
            'App\\Controller\\Admin\\DashboardController::view' => '?',
            'App\\Controller\\BaseController::home' => '?',
            'App\\Controller\\CombatController::accept' => '?',
            'App\\Controller\\CombatController::ajaxData' => '?',
            'App\\Controller\\CombatController::create' => '?',
            'App\\Controller\\CombatController::fight' => '?',
            'App\\Controller\\CombatController::index' => '?',
            'App\\Controller\\CombatController::wait' => '?',
            'App\\Controller\\CombatController::waitData' => '?',
            'App\\Controller\\ContactController::contact' => '?',
            'App\\Controller\\NewsController::index' => '?',
            'App\\Controller\\PersoController::create' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::registerVerificationEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\DashboardController:ContactGestiton' => '?',
            'App\\Controller\\Admin\\DashboardController:UserGestion' => '?',
            'App\\Controller\\Admin\\DashboardController:delete' => '?',
            'App\\Controller\\Admin\\DashboardController:view' => '?',
            'App\\Controller\\BaseController:home' => '?',
            'App\\Controller\\CombatController:accept' => '?',
            'App\\Controller\\CombatController:ajaxData' => '?',
            'App\\Controller\\CombatController:create' => '?',
            'App\\Controller\\CombatController:fight' => '?',
            'App\\Controller\\CombatController:index' => '?',
            'App\\Controller\\CombatController:wait' => '?',
            'App\\Controller\\CombatController:waitData' => '?',
            'App\\Controller\\ContactController:contact' => '?',
            'App\\Controller\\NewsController:index' => '?',
            'App\\Controller\\PersoController:create' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:registerVerificationEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
