<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL26vbvb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL26vbvb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL26vbvb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL26vbvb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL26vbvb\App_KernelDevDebugContainer([
    'container.build_hash' => 'L26vbvb',
    'container.build_id' => '2e94babe',
    'container.build_time' => 1666684558,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL26vbvb');
