<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRG6C1bR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRG6C1bR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRG6C1bR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRG6C1bR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRG6C1bR\App_KernelDevDebugContainer([
    'container.build_hash' => 'RG6C1bR',
    'container.build_id' => 'dba1be92',
    'container.build_time' => 1666691559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRG6C1bR');
